### ISSUE TITLE
Can this package modified to support landscape mode and without status bar?

### ISSUE THREAD

**Issue by bohachu** [tkyaji/UnityIPhoneXSupport#1]
Dear Sir,

We are looking forward a solution to keep old iphone resolution in iPhoneX and found your package. It shows your solution is only support iPhoneX protrait mode with status bar. But our app is designed for landscape mode without status bar. So we wandering is there anyway to modify your code to support our needs? Thanks for your support.

**Comment by tkyaji** [comment]
Supported to landscape orientation with latest version. Please use the `UnityIPhoneXSupport_Landscape.unitypackage`.
